
package ni.jug.ncb.exchangerate.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Tipo de Cambio - Banco Central de Nicaragua
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Tipo_Cambio_BCN", targetNamespace = "http://servicios.bcn.gob.ni/", wsdlLocation = "https://servicios.bcn.gob.ni/Tc_Servicio/ServicioTC.asmx?WSDL")
public class TipoCambioBCN
    extends Service
{

    private final static URL TIPOCAMBIOBCN_WSDL_LOCATION;
    private final static WebServiceException TIPOCAMBIOBCN_EXCEPTION;
    private final static QName TIPOCAMBIOBCN_QNAME = new QName("http://servicios.bcn.gob.ni/", "Tipo_Cambio_BCN");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://servicios.bcn.gob.ni/Tc_Servicio/ServicioTC.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TIPOCAMBIOBCN_WSDL_LOCATION = url;
        TIPOCAMBIOBCN_EXCEPTION = e;
    }

    public TipoCambioBCN() {
        super(__getWsdlLocation(), TIPOCAMBIOBCN_QNAME);
    }

    public TipoCambioBCN(WebServiceFeature... features) {
        super(__getWsdlLocation(), TIPOCAMBIOBCN_QNAME, features);
    }

    public TipoCambioBCN(URL wsdlLocation) {
        super(wsdlLocation, TIPOCAMBIOBCN_QNAME);
    }

    public TipoCambioBCN(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TIPOCAMBIOBCN_QNAME, features);
    }

    public TipoCambioBCN(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TipoCambioBCN(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TipoCambioBCNSoap
     */
    @WebEndpoint(name = "Tipo_Cambio_BCNSoap")
    public TipoCambioBCNSoap getTipoCambioBCNSoap() {
        return super.getPort(new QName("http://servicios.bcn.gob.ni/", "Tipo_Cambio_BCNSoap"), TipoCambioBCNSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TipoCambioBCNSoap
     */
    @WebEndpoint(name = "Tipo_Cambio_BCNSoap")
    public TipoCambioBCNSoap getTipoCambioBCNSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicios.bcn.gob.ni/", "Tipo_Cambio_BCNSoap"), TipoCambioBCNSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TIPOCAMBIOBCN_EXCEPTION!= null) {
            throw TIPOCAMBIOBCN_EXCEPTION;
        }
        return TIPOCAMBIOBCN_WSDL_LOCATION;
    }

}
